### ISSUE TITLE
Error on delete post-it modal confirmation

### ISSUE THREAD

**Issue by RomuloLim** [0horaa/Notes#1]
Hey! When i try to remove a maked post-it, the modal confirmation button is too large. Have you adjust modal width?

**Comment by 0horaa** [comment]
@RomuloLim Hi, thanks to contribute! Can you give me more details about the problem? Why is the modal width bothering you?

**Comment by RomuloLim** [comment]
> @RomuloLim Hi, Thanks to contribute! Can you give me more details about the problem? Why is the modal width bothering you?

The modal have the same width of post-it,  in other words this cause a strange visual look. 🐭

**Comment by 0horaa** [comment]
> > @RomuloLim Hi, Thanks to contribute! Can you give me more details about the problem? Why is the modal width bothering you?
> 
> The modal have the same width of post-it, in other words this cause a strange visual look. 🐭

Aaah, good! You're right, don't worry, I will fix at next updates.

**Comment by RomuloLim** [comment]
> > > @RomuloLim Hi, Thanks to contribute! Can you give me more details about the problem? Why is the modal width bothering you?
> > 
> > 
> > The modal have the same width of post-it, in other words this cause a strange visual look. 🐭
> 
> Aaah, good! You're right, don't worry, I will fix at next updates.

Haha! Thanks for the attention
